# SPDX-License-Identifier: Apache-2.0
# Copyright The Robinauts Authors

"""Pure functions: no IO, no clock, no randomness, no global state.

Every function here is testable with input and output alone; a time it needs
is passed in. It depends on ``robinauts.legacy.domain`` and on nothing else inside
the package (``docs/layout.md``). What sign-in needs is here: the allow list,
the ID token's claims, the URLs, and the configuration's rules. So is what the
conversation format needs: the rules of the tree, the one canonical encoding
of a message, the derived title, and where a run may go next. Fitting a
history into a model's context is **not** here: it is each agent framework's
own (ADR 0005). **One file holds two configurations** -- sign-in and models --
and each parser is handed the whole of it and reads its own share, which is
what ``TOP_LEVEL_KEYS`` is for.
"""

from robinauts.legacy.core.allow import ascii_lower, is_allowed, matches, verified_email
from robinauts.legacy.core.claims import (
    CLOCK_SKEW_SECONDS,
    GMAIL_DOMAINS,
    MAX_ID_TOKEN_CHARS,
    accepted_issuers,
    check_id_token_claims,
    check_published_issuer,
    decode_id_token,
    identity_from_claims,
    identity_from_id_token,
)
from robinauts.legacy.core.conversation_format import (
    EXTRAS,
    MAX_EXTRAS_BYTES,
    MAX_EXTRAS_DEPTH,
    MAX_EXTRAS_NODES,
    MESSAGE_COMPLETED,
    MESSAGE_STARTED,
    REASONING_DELTA,
    RUN_ENDED,
    RUN_STARTED,
    TEXT_DELTA,
    event_from_data,
    event_to_data,
    instant,
    message_from_data,
    message_from_stored,
    message_to_data,
    part_from_data,
    part_to_data,
    provenance_to_data,
    run_event_from_data,
    run_event_from_stored,
    run_event_to_data,
)
from robinauts.legacy.core.conversation_tree import (
    ConversationTree,
    check_answers_calls,
    check_parent,
    check_tree,
    may_follow,
    tree_of,
    tree_of_stored,
)
from robinauts.legacy.core.hashing import (
    MAX_PKCE_CHARS,
    MAX_SECRET_CHARS,
    MIN_SECRET_CHARS,
    UNRESERVED,
    URL_SAFE,
    checked_secret,
    is_secret_shaped,
    pkce_challenge,
    same_secret,
    secret_hash,
)
from robinauts.legacy.core.models_config import (
    AGENT_KEYS,
    ALL_ENGINES,
    ALL_KINDS,
    MODEL_ENTRY_KEYS,
    MODEL_PROVIDER_KEYS,
    TOOL_SERVER_KEYS,
    parse_models_config,
)
from robinauts.legacy.core.oidc import (
    AUTHORIZATION_PARAMETERS,
    MAX_CODE_CHARS,
    TOKEN_PARAMETERS,
    authorization_url,
    parameters_taken,
)
from robinauts.legacy.core.runs import (
    RUN_TRANSITIONS,
    TRUNCATED,
    UNSAID_ERROR,
    ResumePoint,
    active_run,
    active_run_stored,
    check_backend_events,
    check_call_arguments,
    check_event_order,
    check_may_start_run,
    check_may_start_run_stored,
    check_transition,
    may_start_run,
    may_transition,
    resume_point,
    run_error,
    transition,
)
from robinauts.legacy.core.sign_in_config import (
    MODEL_KEYS,
    SIGN_IN_KEYS,
    TOP_LEVEL_KEYS,
    parse_sign_in_config,
)
from robinauts.legacy.core.titles import (
    ELLIPSIS,
    MAX_TITLE_LINES,
    MAX_TITLE_REACH,
    MAX_TITLE_SCAN,
    derive_title,
    first_question,
    title_from_text,
)
from robinauts.legacy.core.urls import (
    DEFAULT_RETURN_TO,
    MAX_RETURN_TO,
    endpoint_query,
    is_loopback,
    normalise_endpoint,
    normalise_issuer,
    normalise_origin,
    safe_return_to,
)

__all__ = [
    "AGENT_KEYS",
    "ALL_ENGINES",
    "ALL_KINDS",
    "AUTHORIZATION_PARAMETERS",
    "CLOCK_SKEW_SECONDS",
    "DEFAULT_RETURN_TO",
    "ELLIPSIS",
    "EXTRAS",
    "GMAIL_DOMAINS",
    "MAX_CODE_CHARS",
    "MAX_EXTRAS_BYTES",
    "MAX_EXTRAS_DEPTH",
    "MAX_EXTRAS_NODES",
    "MAX_ID_TOKEN_CHARS",
    "MAX_PKCE_CHARS",
    "MAX_RETURN_TO",
    "MAX_SECRET_CHARS",
    "MAX_TITLE_LINES",
    "MAX_TITLE_REACH",
    "MAX_TITLE_SCAN",
    "MESSAGE_COMPLETED",
    "MESSAGE_STARTED",
    "MIN_SECRET_CHARS",
    "MODEL_ENTRY_KEYS",
    "MODEL_KEYS",
    "MODEL_PROVIDER_KEYS",
    "REASONING_DELTA",
    "RUN_ENDED",
    "RUN_STARTED",
    "RUN_TRANSITIONS",
    "SIGN_IN_KEYS",
    "TEXT_DELTA",
    "TOKEN_PARAMETERS",
    "TOOL_SERVER_KEYS",
    "TOP_LEVEL_KEYS",
    "TRUNCATED",
    "UNRESERVED",
    "UNSAID_ERROR",
    "URL_SAFE",
    "ConversationTree",
    "ResumePoint",
    "accepted_issuers",
    "active_run",
    "active_run_stored",
    "ascii_lower",
    "authorization_url",
    "check_answers_calls",
    "check_call_arguments",
    "check_backend_events",
    "check_event_order",
    "check_id_token_claims",
    "check_may_start_run",
    "check_may_start_run_stored",
    "check_parent",
    "check_published_issuer",
    "check_transition",
    "check_tree",
    "checked_secret",
    "decode_id_token",
    "derive_title",
    "endpoint_query",
    "event_from_data",
    "event_to_data",
    "first_question",
    "identity_from_claims",
    "identity_from_id_token",
    "instant",
    "is_allowed",
    "is_loopback",
    "is_secret_shaped",
    "matches",
    "may_follow",
    "may_start_run",
    "may_transition",
    "message_from_data",
    "message_from_stored",
    "message_to_data",
    "normalise_endpoint",
    "normalise_issuer",
    "normalise_origin",
    "parameters_taken",
    "parse_models_config",
    "parse_sign_in_config",
    "part_from_data",
    "part_to_data",
    "pkce_challenge",
    "provenance_to_data",
    "resume_point",
    "run_error",
    "run_event_from_data",
    "run_event_from_stored",
    "run_event_to_data",
    "safe_return_to",
    "same_secret",
    "secret_hash",
    "title_from_text",
    "transition",
    "tree_of",
    "tree_of_stored",
    "verified_email",
]
